* Module 1

** Property

Property isn't just objects but rather relates to:

- Rights of ownership
- Possesion over material objects

  
E.G if you rent a property you are in possession of it but the landlord retains ownership. The owner is free to use it, not use it, trash it or sell it. As the legal owner he can do whatever he wants.

If someone was to rent the property from him they can only exercise enjoyment from the property as tenants. So if they caused damage they would have to compensate the landlord for the cost of repair, they also have no rights whatsoever to trash the property.

** Ownership

Ownership rights are:

1) Enjoyment
2) Destruction (subject to the rights of others)
3) Disposition


Different ways of owning property:

1) Creation (you built it bro)
2) Occupation (like squatters rights)
3) Progeny: Say a farmer breeds animals, the offspring will also be his property
4) Property gained through a gift or by purchasing
5) Succession (left behind in a will or inheritance)


All land in England is owned by the crown. Those who actually "own" the land have just purchased freehold possession of it.

** Possession

Possession can be broken into two categories.

1) Corpus Possession.
   It is the intention to own something and the physical control over it. Either direct control or indirect such as an agent. Continuous control.

2) Animus Possidendi
   Control may not be actively exerted but there is an intent to have exclusive control over property. Others would be prohibited from using it.


Possession can happen legally and illegally.
E.G: The landlord owns the freehold over the land. Another may legally be in possession of the land with permission from the owner. But if someone breaks into the house, that is trespassing and they are in illegal possession of the land. (Exception being squatters rights)

*** Relationship

Relationship between ownership and possession. Possession may be used as evidence of ownership. Like when dealing with unregistered land.

* Module 2

** Classification of Property

*** Real Property

Real property relates to freehold land, buildings and the rights over such land. If the owner was unlawfully disposed they are entitled to bring 'real action' against the person who threw them out. If a dispossession was for any other type of property then you would seek compensation for the value of the property rather than repossession.

Rule of thumb: Items that are fixed to the property will come included in any transfer of ownership. Any other item is a chattel.

Some examples of chattels include furniture, refrigerators, washing machines, curtains, beds, and carpets. Chattels are not automatically included in property sales, and the seller would be expected to remove all items under this category before the property changes ownership unless both parties have agreed otherwise.

*** Personal Property

Property not considered real is known as personal property or Chattels.

Personal property can be broken into two categories:

1) Chattels Real
   This usually refers to leasehold land

2) Chattels Personal
   Chattels personal are personal property that are movable and which are not chattels real or real property.


These two can be broken down further into two sub-categories:

- Chooses in action
  Often referred to as incorporeal chattels. (a type of property that is intangible and cannot be physically touched or seen)
  E.G: Goodwill, debt, patents, intellectual rights.

- Chooses in possession
  Often referred to as corporeal chattels. (things you can see and touch) property you can transfer ownership by physical deliveries.
  E.G: Cars, jewellery, electronics etc.

** Fixtures or Chattels

Any Chattels fixed to the land becomes part of the land, a 'fixture'.

#+BEGIN_QUOTE
EXAMPLE
The owner of a mill purchased some looms for use in his mill. They were attached to stone floor by nails driven into wood beams. They could quite easily be removed. The owner then mortgaged the land and failed to keep up the payments and the mill was repossessed. The question for the court was whether the looms were fixtures forming part of the land or whether they remained chattels.

Held: The looms had become fixtures and thus formed part of the land mortgaged.
#+END_QUOTE

Annexation, a formal act whereby a state proclaims its sovereignty over territory hitherto outside its domain.

Prima Facie: A Latin term literally meaning "at first appearance" or "on the face of it". It is used in both civil and criminal law to denote that, on its face, sufficient evidence exists to support a case.

Only the owner (or those lawfully appointed to exercise the rights of an owner) may remove fixtures from land. If a tenant fixes a chattel to the land then only the owner can remove it.

#+BEGIN_QUOTE
EXAMPLE
A tenant in a Ground floor flat with the consent of the landlord purchased some electrical wiring, roofing equipment, wall panels and flooring. He installed them into the conservatory. By doing this they now become property of the landlord as they form part of the flat. When the tenancy came to an end the tenant removed the wiring which involved damaging the wall panels. He was convicted of criminal damage and appealed as he believed he had the right to damage the panels since he paid for them.

Held: His conviction was quashed. He lacked the mens rea of criminal damage as he believed the property he damaged belonged to him. It was irrelevant that the mistake was one of law rather than fact as it related to a mistake of civil law rather than criminal law.
#+END_QUOTE

Chattels found under the surface of the land belong to the landowner. Unless they are items classified as "treasure"

* Module 3

** Land and Estates

*** Land

Definition of land: "Land" includes land of any tenure, mines and minerals, whether or not held apart from the surface, buildings or parts of buildings (whether the division is horizontal, vertical or made in any other way) and other hereditaments; also a manor, advowson, and a rent and other incorporeal hereditaments, and an easement, ... (google this paragraph to find full definition)

- Tenure
  This means the basis upon which land is held (or conditions)

- Estate
  This means the length of time for which the land is held

*** Tenure

#+BEGIN_QUOTE
History Lesson

Free Tenure:
- Military
  This related to land held in return for men to fight for the king
- Spiritual
  Held by the church
- Socage
  Land held for supplying men to work farms
- Serjeanty
  Land held in return for personal services to the king or lord


Unfree Tenure: Land held by people who were lower class and who were sold along with the land.
#+END_QUOTE

** Estates

Speaking of Estates relates to legal interest in the land, referring to what rights the possessor has over the land, how long they are entitled to be there and conditions upon usage of the land.

** Freehold

Freehold relates to the tenure of the property and the legal estate is the fee simple absolute in possession. It can be broken down like

- Fee
  Denotes that the estate is an estate of inheritance. It can be devised by will or inherited under laws of intestacy. (when someone dies without leaving a will)

- Simple
  Denotes that the estate is not a complicated one in that, on death, it is capable of passing to the owner's general heirs.

- Absolute
  Signifies that the estate is not subject to a condition, which will bring it to an end, but will continue forever. Thus it is distinguished from a conditional fee, which, may come to an end on the happening of an event.

- In possession
  Signifies that the grantee must be entitled to immediate possession of the estate. (could be physical possession but in law means being in receipt or being entitled to the rents or profits of the property)


Thus the person holding the fee simple estate will in effect have absolute ownership lasting indefinitely and this ownership can be left to heirs.

Transfer of a freehold from one person to another must be achieved by a deed of conveyance for unregistered or deed of transfer for registered land.

** Leasehold

Leasehold: A leasehold estate is a term of years absolute. Thus meaning the freeholder grants the estate to an individual for a specific period of time. Leases must have a specified length of time. Leases must also grant exclusive possession to the leaseholder.

So in any given lease you will be find these parties:

1) Lessor
   Person granting the lease (also known as landlord)
2) Lessee
   Person who the lease is granted (leaseholder or tenant)


Lessor grants a term of years absolute of possession to the leaseholder. When these years are up the lands reverts back to the lessor. During the lease the lessee will take exclusive possession of the land in return for whatever is requested by the Lessor. (Moolah) If the Lessee breaches the terms of lease, the lessor will be entitled to dispossess the lessee prior to the lease arriving at its conclusion date.

Leasehold estate should be created by way of a deed. Although if a lease that has a term not exceeding 3 years then it doesn't needed to be created by deed. These shorted agreements (tenancies) can be created in less formal documents or even orally.

** Equitable Estates in land

1) Estate in Fee Tail
   This type of estate only descends to a particular class of heirs. E.G all males.

2) Estate for life
   This type of estate remains for the duration of a tenant's life or a third party's life.


Leasehold estate usually arises when a contract to grant a lease is entered into but a formal lease (by way of deed) is not completed.

** Creation of Legal and Equitable Estates

Grants of land by deed may take many forms. Some of these will give a legal estate while others will give an equitable estate. The type given can be established from the title or interest granted to the transferee.

Legal estates:
Must be created by way of deed, can be done in any of the following ways

1) To 'A'
   
2) To 'A' in fee simple (if no date for creation is stated then it is deemed to take immediate effect
   
3) To 'A' and His Heirs (same as 2)


Equitable Estates

1) To A In Tail (this would create a 'Fee Tail' however the tenant has full rights of possession and enjoyment and these would pass on to his heirs upon his death. But heirs could be restricted to a tail male or tail female (descending through males or females only)
   
2) To A for Life (this estate would be granted to 'A' for his life and upon his death the estate terminates. This is called a 'Life Estate'

3) To A as long as B shall survive (the estate continues during the life of another)

   




* Module 4

** Registered land

*** Registered title

All titles must be stored electronically

Proof of ownership is now verified through the register itself rather than the examination of deeds.

Solicitors are provided with copies of the register and must update the register within two month if:

1) A transfer of the freehold (for consideration of by way of gift)

2) A grant of a lease (of more than seven years)

3) An assignment of a lease which at a time of being assigned has more than 7 years remaining

4) The granting of a first legal mortgage

   This is done via the solicitors submitting all title deeds and documents to HMRC who will confirm that stamp duty has been paid. An application will also be submitted for registration, the land registry then investigate the title as it should be and subsequently carry out the registration.

   The land register itself now represents a state backed guarantee that all deeds are correct and represents an official database of the owners of land and the various rights held in land.

*** Priority in Registered Land

The underlying principal of a system of land registration is that a person seeking to require an interest in land need only check the register to determine if the land is subject to any adverse interests. A person who is interested needs to take action to protect that interest by entering it on the register. Generally a purchaser will take free of any interests not on register, however this is not absolute. Depends on the type of interests involved.

A basic rule is that priority between interests in registered land is given by order of creation. Earlier interests will be given priority over the later (on the face of things). First come first serve kind of thing.

*BASIC RULE*

1) The priority of an interest affecting a registered estate or charge is not affected by a disposition of the estate or charge.

2) It makes no difference for the purposes of this section whether the interest or disposition is registered.


In the case of a registered estate the following are the dispositions which are required to be completed by registration.

a) a transfer
b) where the registered estate is an estate in land, the grant of a term of years absolute. (a term of more than 7 years from the date of grant)
c) where the registered estate is a franchise or manor, the grant of a lease
d) the grant of a legal charge

*Equitable Interests behind a trust*

In many instances the question of priority will not arise in relation to equitable interests behind a trust since overreaching will operate to transfer the interests to the proceeds of sale. It is only where the capital moneys are paid to a single trustee that the issue of priority will arise. Where this is the case the beneficial interest may rank as an overriding interest if the occupational requirements are satisfied.

*** Overriding interests in Registered Land.

Overriding interests include leases under 7 years, legal easements and profits a prendre (a right to take something from another person's land), public rights of way, local land charges, mines and minerals, franchises, manorial rights, a right to rent reserved to the crown, non statutory rights in respect of an embankment or sea or river wall, right to payment in lieu of a tithe, a right in respect to the repair of a church. Any interest belonging to a person in actual occupation.

An interest may become overriding in two situations

1) Where the person claiming interest is in actual occupation and that occupation would be obvious on a reasonable inspection or

2) Where the person claiming the interest is in actual occupation and the person to whom the disposition made has actual knowledge of the interest.
   
* Module 5

** Unregistered land and Doctrine of notice

New dispositions of land must be registered. But there what if there is unregistered land.
 
When we say registered or unregistered we are referring to registered or unregistered title. Title refers to proof of ownership.

*** Unregistered Title

Where land is unregistered, proof of ownership will be evidenced by a collection of deeds and documents that will be collectively referred to as the title deeds.

Each time a transfer of ownership takes place additional documents are added to the bundle. Over time this can make the deeds to unregistered land quite large and complex.

*** The Doctrine of Notice - Unregistered Land

Doctrine of notice applied in unregistered land to determine priority of equitable interests not governed by the Land Charges Act 1925

Under the Doctrine of a bona fide purchaser of a legal estate for value takes over any pre-existing equitable interest which is not registrable as a land charge, provided they did not have actual constructive or imputed notice of their existence.

The Doctrine of Notice has no application in registered land where priority is determined by a separate regime including overriding and minor interests. The Doctrine of Notice is therefore relevant in unregistered land where the capital moneys of the conveyance were paid to a single trustee. For a purchaser or mortgagee to acquire the land free of the pre-existing equitable interest they must prove that they are a bona fide purchaser of a legal estate for value without notice.

*Bona Fides*
Is a latin term meaning good faith. The purchaser or mortgagee must demonstrate they acted in good faith in entering the transaction.

*Legal Estate*
This includes a purchase of the freehold, a legal lease or charge by way of legal mortgage

*For Value*
This excludes gifts and conveyances for a nominal consideration. The consideration need not be market value.

*Without Notice*
For the purchaser or mortgagee to take the legal estate free from the equitable interest, they must not have notice (knowledge) of the interest. Where a purchaser or mortgagee is aware or should have been aware of the equitable interest this affects their conscience and they are then bound by the interest.

*Actual Notice*
This is where the purchaser or mortgagee was consciously aware of the existence of the equitable interest.

*Constructive Notice*
Constructive notice is concerned with what the purchaser or mortgagee ought to be aware of or what they would have discovered by making reasonable inquiries.

** Land Charges

Some interests in unregistered land are able to be protected by registration. Called a land charge. Here are the following classes:

*** Classes of Land Charges

- Class A Land charge

  A right to receive money that requires the person entitled to apply for it under an Act of Parliament.

- Class B Land charge

  A right to receive money automatically under an Act of Parliament without needing to apply.

- Class C Land charge (1)

  A puisine mortgage (basically a second mortgage) its not protected by the deposit of legal documents.

- Class C Land charge (2)

  A limited owners charge: an equitable charge for tenants for life or owners who pay Inheritance Tax or other liabilities. Priority given by law.

- Class C Land charge (3)

  A general equitable charge: equitable charge that's not secured by legal documents, not linked to a trust and not covered by other land charge categories.

- Class C Land charge (4)

  Estate contracts: includes a contract to transfer property, options to purchase or rights of pre-emption.

- Class D (1) Land charge

  Inland Revenue Charge

- Class D (2) Land charge

  Restrictive covenants. Only those entered on or after 1st Jan 1926. Restrictive covenants entered before this date are governed by the doctrine of notice.

- Class D (3) Land charge

  Equitable easements. (only those entered on or after 1st Jan 1926

- Class E Land charge

  Annuities created prior to Jan 1st 1926 and not registered to the register of annuities.

- Class F Land charge

  Right of occupation under Part 4 Family Law Act 1996 (protects spouses or other family members, property can't be sold without their knowledge or consent)


*** Registration of Land Charges

A land charge shall be registered in the name of the estate owner whose estate is intended to be affected.

The name should be the same as that found in the conveyance by which the estate had been conveyed.

Where a land charge has been registered in the correct name, this serves as actual notice of its existence. (however if a someone enters a contract to buy the land and a search of the register later reveals a land charge he didn't know about he is not obliged to complete the contract)

Where a land charge is registered in an incorrect name, a subsequent interest may take priority.

** Searches

Searches of land charges register may be personal or official. An official search offers greater protection.

An official search certificate is conclusive even if a mistake was made by the Land Registry. This means a purchaser can rely on the certificate and take priority over any land charges not disclosed on the certificate.

** Unregistered Land Charges

Where a land charge is not registered, the land charge will be void under certain circumstances, (statutory conditions) these statutory conditions are different depending on the class of land charge.

- Class A
  
  A land charge is void against a purchaser of the land or of any interest in the land unless the charge is registered in the appropriate register before the completions of the purchase.

- Class B, C(1), C(2), C(3)

  A land charge of Class B or Class C other than an estate contract is void against a purchaser of the land or of any interest in the land unless the charge is registered in the appropriate register before the completion of the purchase.

- Class C(4) and Class D

  An estate contract and a land charge of Class D created or entered into on or after 1st January 1926 shall be void as against a purchaser or money or money's worth of legal estate in the land charged with it, unless the land charge is registered in the appropriate register.

- Class F

  A land charge of Class F is void against a purchaser of the land or of any interest in the land unless the charge is registered in the appropriate register before the completions of the purchase.

- Exception

  A void land charge may be held to be binding in instances estoppel. (can't go back on their word)
  A person may be estopped from denying the existence of the land charge as held.




* Simplified Terms

*Bona Fides*
This Latin term means "good faith." It means the buyer or lender must show they acted honestly when making the deal.

*Legal Estate*
This refers to ownership of property, which can include buying the freehold, holding a legal lease, or having a legal mortgage.

*For Value*
The transaction must involve something valuable in return, but it doesn't have to be full market value. Free gifts or very small payments don't count.

*Without Notice*
A buyer or lender isn't responsible for hidden interests in the property if they didn't know about them. If they knew or should have known about such claims, they might be bound by them.

*Actual Notice*
This means the buyer or lender was clearly aware of the claim on the property.

*Constructive Interests*
This means the buyer or lender should have known about something if they had made reasonable checks or inquiries. Its about what they ought to know, not just what they actually know.

*Equitable Interest*
An equitable interest is a legal right or claim on a property that isn't full ownership but gives someone a fair share or benefit. For example, if someone has invested in or has a promise related to the property, they may have an equitable interest in it.

*Overriding Interests*
Overriding interests are property rights that bind a new owner or lender, even if they're not registered on the lands official record. These rights "override" the registration system, meaning they still apply without being noted on the title.

*Inland Revenue Charge*
Security for unpaid taxes.
E.G: John Owes 10,000 in unpaid taxes but can't pay. The tax authority places an Inland Revenue charge on his house. This means if John sells the house, the $10,000 must be paid from the sale proceeds before he receives anything. If John still doesn't pay, the tax authority might take legal action to sell the house and collect the debt.

*Equitable Easements*
An equitable easement is a legal agreement that gives the owner of one property the right to restrict the use of another property for the benefit of their own. The main difference between an equitable easement and a legal easement is that an equitable easement only binds a purchaser if they were already aware of it, making it possible to challenge.

*Interest*
Interest itself means someone's legal rights or claims over a piece of property.
